
server:
  port: 8080
  address: localhost  
  session:
    timeout: 60
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/nanshan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 0
    sentinel:
       master: 1
    
mybatis:
mapperLocations: classpath:mapper/*.xml
typeAliasesPackage: com.zyf.dao
configLocation: classpath:mybatis-config.xml
  
encryptionKey: zyf
mail: 
username: zyf


