package com.zyf.dao;

import org.springframework.stereotype.Component;

@Component
public class Killer {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column killer.id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column killer.seckill_id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	private Long seckillId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column killer.user_phone
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	private String userPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column killer.state
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	private Byte state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column killer.id
	 *
	 * @return the value of killer.id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column killer.id
	 *
	 * @param id
	 *            the value for killer.id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column killer.seckill_id
	 *
	 * @return the value of killer.seckill_id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public Long getSeckillId() {
		return seckillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column killer.seckill_id
	 *
	 * @param seckillId
	 *            the value for killer.seckill_id
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public void setSeckillId(Long seckillId) {
		this.seckillId = seckillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column killer.user_phone
	 *
	 * @return the value of killer.user_phone
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column killer.user_phone
	 *
	 * @param userPhone
	 *            the value for killer.user_phone
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column killer.state
	 *
	 * @return the value of killer.state
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column killer.state
	 *
	 * @param state
	 *            the value for killer.state
	 *
	 * @mbggenerated Thu Dec 29 23:18:23 CST 2016
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "Killer [id=" + id + ", seckillId=" + seckillId + ", userPhone="
				+ userPhone + ", state=" + state + "]";
	}

}