package com.zyf.dao.api;

import com.zyf.dao.Killer;

public interface KillerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    int insert(Killer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    int insertSelective(Killer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    Killer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    int updateByPrimaryKeySelective(Killer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table killer
     *
     * @mbggenerated Thu Dec 29 23:18:23 CST 2016
     */
    int updateByPrimaryKey(Killer record);
}